-- BRASEIRO de chão — prop de luz, 64x96, origem nos pés.
-- Amostra do formato DSL (Fase 0, docs/MEGAPLAN_VISUAL_HD.md §1-2).
-- Tripé de ferro com ferrugem, tigela de brasas e labaredas.
-- Prova do emissivo: chama ei=1 (estoura no bloom), brasas ei~0.7.
-- Relevo: chama/tigela altos (h 9-15), base do tripé baixa (h 3).

local function L(s)
    assert(#s <= 64, 'linha de sprite > 64 colunas')
    return s .. string.rep('.', 64 - #s)
end
local function grid(rows) return table.concat(rows, '\n') end
local E = string.rep('.', 64)

return {
    name = 'braseiro',
    w = 64, h = 96,
    origin = 'feet',

    legend = {
        k = {spec = 'ink', h = 4},
        -- ferro da tigela (I = borda iluminada, h alto) e das pernas (L, baixo)
        i = {ramp = 'iron', step = 3, h = 8},
        I = {ramp = 'iron', step = 5, h = 10},
        L = {ramp = 'iron', step = 2, h = 3},
        -- ferrugem na tigela (r) e nas pernas (R)
        r = {ramp = 'rust', step = 3, h = 8},
        R = {ramp = 'rust', step = 2, h = 3},
        -- brasas na tigela: emissivo moderado
        e = {ramp = 'ember', step = 2, h = 9, e = 'ember.3', ei = 0.7},
        o = {ramp = 'ember', step = 4, h = 9, e = 'ember.5', ei = 0.7},
        -- labareda: f = borda, F = corpo, O = núcleo quente — ei 1, bloom forte
        f = {ramp = 'ember', step = 3, h = 13, e = 'ember.4', ei = 1},
        F = {ramp = 'ember', step = 5, h = 14, e = 'ember.6', ei = 1},
        O = {ramp = 'ember', step = 7, h = 15, e = 'ember.7', ei = 1},
    },

    layers = {
        {   -- BASE: tigela de ferro com brasas + tripé até os pés
            name = 'base',
            h = 3,
            albedo = grid {
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E,
                -- borda da tigela (cols 14-50)
                L'.............kIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIk',
                L'.............kiiiiiiieeoeeeeeeoeeoeeeeoeeeiiiiiiik',
                L'.............kiiiiiiieeoeeeeeeoeeoeeeeoeeeiiiiiiik',
                L'.............kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik',
                -- bojo da tigela afinando para o colar (cols 16-48 -> 22-42)
                L'...............kiiiiiiiiiirriiiiiiirriiiiiiiik',
                L'...............kiiiiiiiiiirriiiiiiirriiiiiiiik',
                L'...............kiiiiiiiiiirriiiiiiirriiiiiiiik',
                L'...............kiiiiiiiiiirriiiiiiirriiiiiiiik',
                L'.................kiiiiiirriiiiiiiiiirriiiiik',
                L'.................kiiiiiirriiiiiiiiiirriiiiik',
                L'.................kiiiiiirriiiiiiiiiirriiiiik',
                L'.................kiiiiiirriiiiiiiiiirriiiiik',
                L'...................kiiiiirriiiiiiiiiiirriiiik',
                L'...................kiiiiirriiiiiiiiiiirriiiik',
                L'...................kiiiiirriiiiiiiiiiirriiiik',
                L'...................kiiiiirriiiiiiiiiiirriiiik',
                L'.....................kiiiriiiiiiiiirriik',
                L'.....................kiiiriiiiiiiiirriik',
                -- colar e nó do tripé
                L'...........................kiiiiriiiik',
                L'...........................kiiiiriiiik',
                L'...........................kiiiiriiiik',
                L'.........................kiiiiriiiiiiik',
                L'.........................kiiiiriiiiiiik',
                L'.........................kiiiiriiiiiiik',
                -- três pernas em splay até o chão
                L'...........................LL.LLLLL',
                L'..........................LL..LLL.LL',
                L'..........................LL..LLL.LL',
                L'.........................LR...LLL..LR',
                L'.........................LL...LLL..LL',
                L'........................LL....LLL...LL',
                L'........................LL....LLL...LL',
                L'.......................LL.....LLR....LL',
                L'.......................LL.....LLL....LL',
                L'......................LL......LLL.....LL',
                L'......................LR......LLL.....LR',
                L'.....................LL.......LLL......LL',
                L'.....................LL.......LLL......LL',
                L'....................LL........LLL.......LL',
                L'....................LL........LLR.......LL',
                L'....................LL........LLL.......LL',
                L'...................LL.........LLL........LL',
                L'...................LR.........LLL........LR',
                L'..................LL..........LLL.........LL',
                L'..................LL..........LLL.........LL',
                L'.................LL...........LLL..........LL',
                L'.................LL...........LLL..........LL',
                L'................LL............LLL...........LL',
                L'................LL............LLL...........LL',
                L'...............LR.............LLL............LR',
                L'...............LL.............LLL............LL',
                L'..............LL..............LLL.............LL',
                L'..............LL..............LLL.............LL',
                L'.............LL...............LLL..............LL',
                -- patas: apoio lateral e pé central
                L'............kLLk..............LLL.............kLLk',
                L'............kLLk..............LLL.............kLLk',
                L'.............................kLLLk',
                L'.............................kLLLk',
            },
        },
        {   -- FIRE: labareda sobre a tigela + emissivo da chama e das brasas
            name = 'fire',
            h = 14,
            albedo = grid {
                E, E, E, E, E,
                L'................................f',
                L'................................f',
                L'...............................fFf',
                L'..............................ffFFf',
                L'..............................ffFFf',
                L'.............................ffFOFff',
                L'.............................ffFOFff',
                L'........................f..fffFOFfff',
                L'.......................fff.fffFOOfff',
                L'.......................fffffffFOOfff',
                L'.......................ffFffFOOOFffff',
                L'......................ffffffFOOOFffff',
                L'......................fffffffOOOFfffff.ff',
                L'......................fffffFFOOOOOfffffff',
                L'......................ffffFFOOOOOOffffffff',
                L'......................ffffFOOOOOOOfffffff',
                L'......................ffffOOOOOOOOffffffff',
                L'......................ffffOOOOOOOOffffffff',
                L'......................fffOOOOOOOOOfffffff',
                L'......................fffOOOOOOOOOfffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'.....................fffOOOOOOOOOOfffffff',
                L'.....................fffOOOOOOOOOOfffffff',
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E,
            },
            -- Emissivo: mesma forma da chama (ei 1) + leito de brasas (ei .7).
            emissive = grid {
                E, E, E, E, E,
                L'................................f',
                L'................................f',
                L'...............................fFf',
                L'..............................ffFFf',
                L'..............................ffFFf',
                L'.............................ffFOFff',
                L'.............................ffFOFff',
                L'........................f..fffFOFfff',
                L'.......................fff.fffFOOfff',
                L'.......................fffffffFOOfff',
                L'.......................ffFffFOOOFffff',
                L'......................ffffffFOOOFffff',
                L'......................fffffffOOOFfffff.ff',
                L'......................fffffFFOOOOOfffffff',
                L'......................ffffFFOOOOOOffffffff',
                L'......................ffffFOOOOOOOfffffff',
                L'......................ffffOOOOOOOOffffffff',
                L'......................ffffOOOOOOOOffffffff',
                L'......................fffOOOOOOOOOfffffff',
                L'......................fffOOOOOOOOOfffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffffOOOOOOOOOffffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'.....................ffFOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'....................ffffOOOOOOOOOOOfffffff',
                L'.....................fffOOOOOOOOOOfffffff',
                L'.....................fffOOOOOOOOOOfffffff',
                E, E,
                L'......................eeoeeeeeeoeeoeeeeoeee',
                L'......................eeoeeeeeeoeeoeeeeoeee',
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E,
            },
        },
    },
}
