-- Sprites DSL do padrão HD (Fases 0-3, docs/MEGAPLAN_VISUAL_HD.md).
-- Cada módulo retorna uma def p/ SpriteDSL.bake(). Frames servem de
-- animação (walk/idle), variantes por seed (tiles/props), estados por
-- flag (f1=inicial) e telegraph (foe_*: [idle1,idle2,warn]).
-- Convenções e nomes: nota maestri assets-fase1.
return {
    -- Amostras Fase 0
    viajante = require('src.sprites.viajante'),
    braseiro = require('src.sprites.braseiro'),
    parede = require('src.sprites.parede'),
    -- Tiles Refugio
    piso_laje = require('src.sprites.piso_laje'),
    piso_terra = require('src.sprites.piso_terra'),
    piso_grama = require('src.sprites.piso_grama'),
    piso_caminho = require('src.sprites.piso_caminho'),
    piso_horta = require('src.sprites.piso_horta'),
    piso_tabua = require('src.sprites.piso_tabua'),
    -- Tiles Colina
    piso_colina = require('src.sprites.piso_colina'),
    -- Arquitetura
    parede_canto_e = require('src.sprites.parede_canto_e'),
    parede_canto_d = require('src.sprites.parede_canto_d'),
    parede_janela = require('src.sprites.parede_janela'),
    parede_porta = require('src.sprites.parede_porta'),
    parede_painel = require('src.sprites.parede_painel'),
    parede_painel_janela = require('src.sprites.parede_painel_janela'),
    pilar = require('src.sprites.pilar'),
    marco = require('src.sprites.marco'),
    remendo_muro = require('src.sprites.remendo_muro'),
    parapeito = require('src.sprites.parapeito'),
    -- Praca/ruas
    lampiao = require('src.sprites.lampiao'),
    banco_madeira = require('src.sprites.banco_madeira'),
    banco_pedra = require('src.sprites.banco_pedra'),
    banco_serra = require('src.sprites.banco_serra'),
    varal = require('src.sprites.varal'),
    toldo = require('src.sprites.toldo'),
    recipientes = require('src.sprites.recipientes'),
    cartaz = require('src.sprites.cartaz'),
    posto_vigia = require('src.sprites.posto_vigia'),
    rocha = require('src.sprites.rocha'),
    placa = require('src.sprites.placa'),
    -- Horta/terraco
    espantalho = require('src.sprites.espantalho'),
    canteiro_a = require('src.sprites.canteiro_a'),
    canteiro_b = require('src.sprites.canteiro_b'),
    rack_ervas = require('src.sprites.rack_ervas'),
    fardos = require('src.sprites.fardos'),
    banco_terraco = require('src.sprites.banco_terraco'),
    varal_terraco = require('src.sprites.varal_terraco'),
    cisterna_rua = require('src.sprites.cisterna_rua'),
    -- Quintal da forja
    bigorna = require('src.sprites.bigorna'),
    brasa_forja = require('src.sprites.brasa_forja'),
    pilha_lenha = require('src.sprites.pilha_lenha'),
    balde_tempera = require('src.sprites.balde_tempera'),
    entulho = require('src.sprites.entulho'),
    madeira_encostada = require('src.sprites.madeira_encostada'),
    -- Adro
    mureta_adro = require('src.sprites.mureta_adro'),
    portao_adro = require('src.sprites.portao_adro'),
    flores_adro = require('src.sprites.flores_adro'),
    oferenda = require('src.sprites.oferenda'),
    marca_impro = require('src.sprites.marca_impro'),
    -- Colina
    lapide_a = require('src.sprites.lapide_a'),
    lapide_b = require('src.sprites.lapide_b'),
    lapide_c = require('src.sprites.lapide_c'),
    vela_votiva = require('src.sprites.vela_votiva'),
    cova = require('src.sprites.cova'),
    cipo = require('src.sprites.cipo'),
    muro_colina = require('src.sprites.muro_colina'),
    -- Interiores — cozinha
    fogao = require('src.sprites.fogao'),
    mesa_longa = require('src.sprites.mesa_longa'),
    prateleira = require('src.sprites.prateleira'),
    tigela = require('src.sprites.tigela'),
    -- Interiores — capela
    altar = require('src.sprites.altar'),
    banco_capela = require('src.sprites.banco_capela'),
    velas = require('src.sprites.velas'),
    mesa_oferenda = require('src.sprites.mesa_oferenda'),
    quadro = require('src.sprites.quadro'),
    -- Interiores — casa das camas
    cama = require('src.sprites.cama'),
    divisoria = require('src.sprites.divisoria'),
    pertences = require('src.sprites.pertences'),
    bau = require('src.sprites.bau'),
    brinquedo = require('src.sprites.brinquedo'),
    -- Interiores — oficina
    bancada = require('src.sprites.bancada'),
    rack_ferramentas = require('src.sprites.rack_ferramentas'),
    peca_inacabada = require('src.sprites.peca_inacabada'),
    serragem = require('src.sprites.serragem'),
    -- Interiores — escola
    carteiras = require('src.sprites.carteiras'),
    caixas_antigas = require('src.sprites.caixas_antigas'),
    quadro_aula = require('src.sprites.quadro_aula'),
    estante = require('src.sprites.estante'),
    -- Props diversos
    poco = require('src.sprites.poco'),
    mesa = require('src.sprites.mesa'),
    cadeira = require('src.sprites.cadeira'),
    cercado = require('src.sprites.cercado'),
    arvore = require('src.sprites.arvore'),
    -- Casas multi-tile (128-192px) + arena + ambientais animados
    casa_fachada_a = require('src.sprites.casa_fachada_a'),
    casa_fachada_b = require('src.sprites.casa_fachada_b'),
    casa_pensao = require('src.sprites.casa_pensao'),
    casa_telhado = require('src.sprites.casa_telhado'),
    piso_arena = require('src.sprites.piso_arena'),
    tocha = require('src.sprites.tocha'),
    varal_vento = require('src.sprites.varal_vento'),
    vela_votiva_anim = require('src.sprites.vela_votiva_anim'),
    fumaca_chamine = require('src.sprites.fumaca_chamine'),
    -- W5 (Tinta): borda de transição de terreno + estados de gameplay
    piso_terra_borda = require('src.sprites.piso_terra_borda'),
    braseiro_quiet = require('src.sprites.braseiro_quiet'),
    varal_vento_quiet = require('src.sprites.varal_vento_quiet'),
    -- W6 (Tinta): efeitos autorados via src/kit_vfx (V.sheet)
    fx_tiro = require('src.sprites.fx_tiro'),
    fx_hit_jade = require('src.sprites.fx_hit_jade'),
    fx_bloco = require('src.sprites.fx_bloco'),
    fx_morte = require('src.sprites.fx_morte'),
    -- Atores — viajante
    viajante_n = require('src.sprites.viajante_n'),
    viajante_e = require('src.sprites.viajante_e'),
    viajante_w = require('src.sprites.viajante_w'),
    viajante_walk_s = require('src.sprites.viajante_walk_s'),
    viajante_walk_n = require('src.sprites.viajante_walk_n'),
    viajante_walk_e = require('src.sprites.viajante_walk_e'),
    viajante_walk_w = require('src.sprites.viajante_walk_w'),
    -- Atores — viajante acoes (W4: anchors/markers/sequences/frameDuration)
    viajante_tiro_s = require('src.sprites.viajante_tiro_s'),
    viajante_tiro_e = require('src.sprites.viajante_tiro_e'),
    viajante_tiro_w = require('src.sprites.viajante_tiro_w'),
    viajante_tiro_n = require('src.sprites.viajante_tiro_n'),
    viajante_interacao = require('src.sprites.viajante_interacao'),
    -- Atores — NPCs
    npc_doro_s = require('src.sprites.npc_doro_s'),
    npc_doro_n = require('src.sprites.npc_doro_n'),
    npc_doro_e = require('src.sprites.npc_doro_e'),
    npc_doro_w = require('src.sprites.npc_doro_w'),
    npc_aurel_s = require('src.sprites.npc_aurel_s'),
    npc_aurel_n = require('src.sprites.npc_aurel_n'),
    npc_aurel_e = require('src.sprites.npc_aurel_e'),
    npc_aurel_w = require('src.sprites.npc_aurel_w'),
    npc_sabela_s = require('src.sprites.npc_sabela_s'),
    npc_sabela_n = require('src.sprites.npc_sabela_n'),
    npc_sabela_e = require('src.sprites.npc_sabela_e'),
    npc_sabela_w = require('src.sprites.npc_sabela_w'),
    npc_bento_s = require('src.sprites.npc_bento_s'),
    npc_bento_n = require('src.sprites.npc_bento_n'),
    npc_bento_e = require('src.sprites.npc_bento_e'),
    npc_bento_w = require('src.sprites.npc_bento_w'),
    npc_teca_s = require('src.sprites.npc_teca_s'),
    npc_teca_n = require('src.sprites.npc_teca_n'),
    npc_teca_e = require('src.sprites.npc_teca_e'),
    npc_teca_w = require('src.sprites.npc_teca_w'),
    npc_nilo_s = require('src.sprites.npc_nilo_s'),
    npc_nilo_n = require('src.sprites.npc_nilo_n'),
    npc_nilo_e = require('src.sprites.npc_nilo_e'),
    npc_nilo_w = require('src.sprites.npc_nilo_w'),
    -- Atores — loops de trabalho (4f, sul)
    npc_doro_trabalho = require('src.sprites.npc_doro_trabalho'),
    npc_aurel_trabalho = require('src.sprites.npc_aurel_trabalho'),
    npc_sabela_trabalho = require('src.sprites.npc_sabela_trabalho'),
    npc_bento_trabalho = require('src.sprites.npc_bento_trabalho'),
    npc_teca_trabalho = require('src.sprites.npc_teca_trabalho'),
    npc_nilo_trabalho = require('src.sprites.npc_nilo_trabalho'),
    -- Atores — ecos da arena
    foe_crawler = require('src.sprites.foe_crawler'),
    foe_dasher = require('src.sprites.foe_dasher'),
    foe_ranger = require('src.sprites.foe_ranger'),
    foe_sower = require('src.sprites.foe_sower'),
    foe_breaker = require('src.sprites.foe_breaker'),
    foe_watcher = require('src.sprites.foe_watcher'),
    foe_veteran = require('src.sprites.foe_veteran'),
    foe_husk = require('src.sprites.foe_husk'),
    foe_warden = require('src.sprites.foe_warden'),
    foe_demolisher = require('src.sprites.foe_demolisher'),
    foe_regent = require('src.sprites.foe_regent'),
    -- Retratos de diálogo 96x96 topleft (frames = expressoes: f1 neutro)
    portrait_viajante = require('src.sprites.portrait_viajante'),
    portrait_doro = require('src.sprites.portrait_doro'),
    portrait_aurel = require('src.sprites.portrait_aurel'),
    portrait_sabela = require('src.sprites.portrait_sabela'),
    portrait_bento = require('src.sprites.portrait_bento'),
    portrait_runa = require('src.sprites.portrait_runa'),
    -- Atores — chefe
    boss_runa_s = require('src.sprites.boss_runa_s'),
    boss_runa_n = require('src.sprites.boss_runa_n'),
    boss_runa_e = require('src.sprites.boss_runa_e'),
    boss_runa_w = require('src.sprites.boss_runa_w'),
}
