-- O VIAJANTE — protagonista, idle de frente (sul), 64x96, origem nos pés.
-- Amostra do formato DSL (Fase 0, docs/MEGAPLAN_VISUAL_HD.md §1-2).
-- Âncoras visuais (docs/PERSONAGENS_DIRECAO_VISUAL_E_NARRATIVA.md §1):
--   arco lateral alto | aba assimétrica do casaco | remendo claro no ombro.
-- Ficha: casaco marrom frio até metade da coxa, aba presa para caminhar,
-- remendo ocre no ombro, camisa de linho cru, colete de lã verde desbotado,
-- calças carvão com joelhos reforçados, botas castanhas de sola remendada.
--
-- Convenções assumidas (confirmar com src/sprite_dsl.lua):
--   'rampa.step' = índice na rampa, 1 = mais escuro, subindo = mais claro.
--   '.' ou ' ' = vazio; canais compõem por camada, último não-vazio vence.
--   h = relevo 0..15 usado no bake do normal (cabeça > tronco > botas).

-- Auxiliares de grade: cada linha é dots à esquerda + conteúdo, completada
-- com '.' à direita até 64 colunas. Assert pega linha estourada na carga.
local function L(s)
    assert(#s <= 64, 'linha de sprite > 64 colunas')
    return s .. string.rep('.', 64 - #s)
end
local function grid(rows) return table.concat(rows, '\n') end
local E = string.rep('.', 64) -- linha vazia

return {
    name = 'viajante',
    w = 64, h = 96,
    origin = 'feet',

    legend = {
        -- contorno (funcional, sem degrau)
        k = {spec = 'ink', h = 4},
        -- cabelo preto ondulado, amarrado baixo
        h = {ramp = 'hair', step = 1, h = 11},
        H = {ramp = 'hair', step = 4, h = 12},
        -- pele castanha quente; S = luz no nariz/testa; d = sombra/barba
        s = {ramp = 'skin', step = 4, h = 11},
        S = {ramp = 'skin', step = 5, h = 12},
        d = {ramp = 'skin', step = 3, h = 10},
        e = {spec = 'ink', h = 12}, -- olhos e boca
        -- camisa de linho cru / colete de lã verde desbotado
        l = {ramp = 'plaster', step = 5, h = 6},
        v = {ramp = 'moss', step = 3, h = 6},
        r = {ramp = 'earth', step = 2, h = 5}, -- cinto
        n = {ramp = 'gold', step = 5, h = 7}, -- fivela e fecho do casaco
        -- calças carvão (cinza-ferro); K = joelhos reforçados
        p = {ramp = 'iron', step = 2, h = 4},
        K = {ramp = 'iron', step = 3, h = 5},
        -- botas castanhas; o = sola remendada mais clara
        b = {ramp = 'earth', step = 2, h = 2},
        B = {ramp = 'earth', step = 4, h = 3},
        o = {ramp = 'earth', step = 5, h = 2},
        -- casaco marrom frio (taupe de terra); x = sombra/bainha; C = punho
        c = {ramp = 'earth', step = 3, h = 7},
        x = {ramp = 'earth', step = 2, h = 6},
        C = {ramp = 'earth', step = 5, h = 7},
        m = {ramp = 'gold', step = 5, h = 7}, -- REMENDO OCRE no ombro
        -- arco de madeira; t = corda; aljava e flechas
        w = {ramp = 'wood', step = 3, h = 5},
        W = {ramp = 'wood', step = 5, h = 6},
        t = {ramp = 'bone', step = 4, h = 4},
        T = {ramp = 'earth', step = 2, h = 9}, -- cordão do pingente
        q = {ramp = 'earth', step = 4, h = 7},
        Q = {ramp = 'earth', step = 2, h = 7},
        a = {ramp = 'wood', step = 5, h = 7},
        f = {ramp = 'bone', step = 5, h = 7},
        -- pingente jade discreto: prova do canal emissivo (ei ~0.8)
        j = {spec = 'jade', h = 9, e = 'jadeLight', ei = 0.8},
    },

    layers = {
        {   -- BODY: rosto/cabelo, camisa+colete, mãos, calças, botas
            name = 'body',
            h = 4,
            albedo = grid {
                E, E, E, E, E,
                L'.............................kkkkkkk',
                L'..........................khhhhhhhhhhk',
                L'.........................khhhhhhhhhhhhhk',
                L'.........................khhhhhHhhhhhhhk',
                L'.........................khhhhhhhhhhhhhk',
                L'.........................khhssssssssshhk',
                L'.........................khssssssssssshk',
                L'.........................khssssssssssshk',
                L'.........................ksssssssssssssk',
                L'.........................kssddddsddddssk',
                L'.........................ksseessssseessk',
                L'.........................kddsssssssssddk',
                L'.........................kdsssssssssssdk',
                L'..........................dsssssSSssssd',
                L'..........................dssssSSSSssssd',
                L'..........................dsssssSSssssd',
                L'..........................dddssssssssddd',
                L'..........................ddseesssssddd',
                L'..........................dddhhhhhhhddd',
                L'...........................ddhhhhhhhdd',
                L'...........................dddhhhhhddd',
                L'............................kddhhhddk',
                L'.............................kdddddk',
                L'.............................ksssssk',
                L'.............................ksssssk',
                L'.............................ksssssk',
                L'........................klllllllllllllllllk',
                L'........................klllllllllllllllllk',
                L'........................klllllllllllllllllk',
                L'........................klllllllllllllllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'........................klllvvvvvvvvvvllllk',
                L'...................kssssklllvvvvvvvvvvllllkssssk',
                L'...................ksssskrrrrrrrnnrrrrrrrrkssssk',
                L'...................ksssskrrrrrrrnnrrrrrrrrkssssk',
                L'...................ksssskpppppppppppppppppkssssk',
                L'...................kssss.kppppppkpppppppk.ssssk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kppppppkpppppppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'.........................kpKKKKpkppKKKKppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'..........................kpppppkpppppppk',
                L'...........................kppppkpppppk',
                L'...........................kppppkpppppk',
                L'...........................kppppkpppppk',
                L'........................kbbbbbbbk.kbbbbbbbk',
                L'........................kbbbbbbbk.kbbbbbbbk',
                L'........................kbbbbbbbk.kbbbbbbbk',
                L'........................kbbbbbbbk.kbbbbbbbk',
                L'........................kbbbbbbbk.kbbbbbbbk',
                L'.......................kbbbbbbbbbk.kbbbbbbbbbk',
                L'.......................kbbbbbbbbbk.kbbbbbbbbbk',
                L'.......................kbbbbbbbbbk.kbbbbbbbbbk',
                L'.......................kbbbbbbbbbk.kbbbbbbbbbk',
                L'.......................kbbbbbbbbbk.kbbbbbbbbbk',
                L'.......................kooooooooook.kBBBBBBBBBk',
                L'.......................kkkkkkkkkkk.kkkkkkkkkkk',
                E,
            },
        },
        {   -- COAT: casaco marrom — aba assimétrica (direita presa/curta),
            -- remendo ocre no ombro esquerdo do sprite, punhos claros.
            name = 'coat',
            h = 7,
            albedo = grid {
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E,
                L'.......................kccccccccccccccccccck',
                L'......................kcccccccccccccccccccccck',
                L'.....................kccccccccccccccccccccccck',
                L'.....................kcmmmmcccccccccccccccccck',
                L'.....................kcmmmmmmcccccccccccccccck',
                L'.....................kccmmmmmmcccccccccccccck',
                L'.....................kccmmmmccccccccccccccxxk',
                L'.....................kcccmmccccccccccccccccxxk',
                L'.....................kccccccx........xccccccck',
                L'.....................kccccccx........xccccccck',
                L'.....................kcccccxn........xccccccck',
                L'.....................kcccccxn........xccccccck',
                L'......................kcccccx........xcccccck',
                L'......................kcccccx........xcccccck',
                L'......................kcccccx........xcccccck',
                L'......................kcccccx........xcccccck',
                L'......................kcccccx........xcccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kCCCCx........xCCCCk',
                L'........................kcccx........xcccck',
                L'........................kcccx........xcccck',
                L'........................kcccx........xcccck',
                L'........................kcccx........xcccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccck',
                L'.......................kccccx........xccccnk',
                L'.......................kccccx........xCCCCCx',
                L'.......................kccccx........xCCCCCx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcccccx',
                L'......................kcxxxxk',
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E,
            },
        },
        {   -- GEAR: arco alto na lateral esquerda (empunhado), aljava de
            -- quadril à direita com hastes e penas, pingente jade no peito.
            name = 'gear',
            h = 6,
            albedo = grid {
                E, E, E, E,
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t..........T',
                L'..................wW.t..........T',
                L'..................wW.t..........T',
                L'..................wW.t..........T',
                L'..................wW.t.........jjj',
                L'..................wW.t..........j',
                L'..................wWWt',
                L'..................wWWt.........................f.f.f',
                L'..................wWWt.........................a.a.a',
                L'..................wWWt.........................a.a.a',
                L'..................wWWt........................kqqqqqqk',
                L'..................wWWt........................kqqqqqqk',
                L'..................wWWt........................kqqqqqQk',
                L'..................wWWt........................kqqqqqQk',
                L'..................wWWt........................kqqqqqQk',
                L'..................wWWt........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t........................kqqqqqQk',
                L'..................wW.t.........................kqqqqk',
                L'..................wW.t.........................kqqqqk',
                L'..................wW.t.........................kqqqqk',
                L'..................wW.t..........................kqk',
                L'..................wW.t',
                L'..................wW.t',
                L'..................wW.t',
                L'.................ww..t',
                L'.................ww..t',
                L'.................ww..t',
                L'.................ww..t',
                L'.................ww..t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w...t',
                L'.................w',
                L'.................w',
                L'.................w',
                E, E, E, E, E, E, E, E,
            },
            -- Emissivo: só o pingente jade (4 px, ei 0.8 via legend).
            emissive = grid {
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E,
                L'................................jjj',
                L'.................................j',
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E, E, E,
                E, E, E, E, E, E, E, E,
            },
        },
    },
}
