-- Cinco interiores autorais pequenos; as portas são percursos locais, sem viagem.
return {
    capela = {
        id = 'capela', uid = 21, name = 'CAPELA DO REFÚGIO', realm = 'refugio', w = 11, h = 10,
        spawn = {x = 6, y = 8}, arrivals = {hub = {x = 6, y = 8, dy = -1}},
        carve = {{x = 2, y = 2, w = 8, h = 7}},
        props = {{id = 'altar', kind = 'altar', x = 5, y = 3, w = 2, solid = true},
            {id = 'banco1', kind = 'banco', x = 3, y = 5, w = 2, solid = true},
            {id = 'banco2', kind = 'banco', x = 7, y = 5, w = 2, solid = true},
            {id = 'oferenda', kind = 'mesa', x = 3, y = 4, solid = true},
            {id = 'quadroCapela', kind = 'quadro', x = 4, y = 2},
            {id = 'bancoFundo', kind = 'banco', x = 8, y = 7, w = 2, solid = true}},
        npcs = {{id = 'doro', x = 5, y = 4, act = 'sweep'}},
        hotspots = {{id = 'altar', x = 5, y = 3, range = 1.7, label = 'EXAMINAR'}},
        exits = {{x = 6, y = 9, to = 'hub', arrival = 'capela', localPath = true, label = 'PRAÇA'}},
    },
    cozinha = {
        id = 'cozinha', uid = 22, name = 'COZINHA DO REFÚGIO', realm = 'refugio', w = 12, h = 10,
        spawn = {x = 7, y = 8}, arrivals = {hub = {x = 7, y = 8, dy = -1}},
        carve = {{x = 2, y = 2, w = 9, h = 7}},
        props = {{id = 'fogao', kind = 'fogao', x = 3, y = 3, solid = true},
            {id = 'mesa', kind = 'mesa', x = 7, y = 4, w = 2, solid = true},
            {id = 'caixas', kind = 'caixas', x = 10, y = 3, solid = true},
            {id = 'prateleira', kind = 'prateleira', x = 10, y = 2, solid = true},
            {id = 'quadroCozinha', kind = 'quadro', x = 5, y = 2}},
        npcs = {{id = 'bento', x = 4, y = 4, act = 'stir'}},
        hotspots = {{id = 'refeicaoRefugio', x = 7, y = 4, range = 1.7, label = 'COMER'},
            {id = 'prateleiraRefugio', x = 9, y = 3, label = 'EXAMINAR'}},
        exits = {{x = 7, y = 9, to = 'hub', arrival = 'cozinha', localPath = true, label = 'RUA BAIXA'}},
    },
    pensao = {
        id = 'pensao', uid = 23, name = 'CASA DAS CAMAS', realm = 'refugio', w = 13, h = 10,
        spawn = {x = 6, y = 8}, arrivals = {hub = {x = 6, y = 8, dy = -1}},
        carve = {{x = 2, y = 2, w = 10, h = 7}},
        props = {{id = 'cama1', kind = 'cama', x = 3, y = 3, solid = true},
            {id = 'cama2', kind = 'cama', x = 6, y = 3, solid = true},
            {id = 'cama3', kind = 'cama', x = 9, y = 3, solid = true},
            {id = 'divisoria1', kind = 'divisoria', x = 5, y = 3, solid = true},
            {id = 'divisoriaAberta', kind = 'divisoria', x = 8, y = 3, solid = true},
            {id = 'bauPensao', kind = 'bau', x = 10, y = 6, solid = true},
            {id = 'quadroPensao', kind = 'quadro', x = 4, y = 2},
            {id = 'pertencesCama1', kind = 'pertences', x = 4, y = 3},
            {id = 'pertencesCama2', kind = 'pertences', x = 7, y = 3},
            {id = 'pertencesCama3', kind = 'pertences', x = 10, y = 3},
            {id = 'brinquedoPensao', kind = 'brinquedo', x = 4, y = 5}},
        hotspots = {{id = 'descansoRefugio', x = 6, y = 3, label = 'DESCANSAR'},
            {id = 'camasRefugio', x = 8, y = 4, label = 'EXAMINAR'},
            {id = 'bauRefugio', x = 10, y = 6, label = 'EXAMINAR'}},
        exits = {{x = 6, y = 9, to = 'hub', arrival = 'pensao', localPath = true, label = 'RUA DAS CAMAS'}},
    },
    oficina = {
        id = 'oficina', uid = 24, name = 'FORJA E BANCADA', realm = 'refugio', w = 11, h = 10,
        spawn = {x = 6, y = 8}, arrivals = {hub = {x = 6, y = 8, dy = -1}},
        carve = {{x = 2, y = 2, w = 8, h = 7}},
        props = {{id = 'bancada', kind = 'bancada', x = 4, y = 3, w = 2, solid = true},
            {id = 'ferramentas', kind = 'ferramentas', x = 8, y = 3, solid = true},
            {id = 'panoBancada', kind = 'pano', x = 5, y = 3},
            {id = 'serragem', kind = 'serragem', x = 6, y = 4}},
        npcs = {{id = 'nilo', x = 6, y = 5, act = 'tinker'}},
        hotspots = {{id = 'preparoRefugio', x = 4, y = 3, range = 1.7, label = 'PREPARAR'}},
        exits = {{x = 6, y = 9, to = 'hub', arrival = 'oficina', localPath = true, label = 'QUINTAL DA FORJA'}},
    },
    escola = {
        id = 'escola', uid = 25, name = 'DEPÓSITO E ESCOLA', realm = 'refugio', w = 12, h = 10,
        spawn = {x = 7, y = 8}, arrivals = {hub = {x = 7, y = 8, dy = -1}},
        carve = {{x = 2, y = 2, w = 9, h = 7}},
        props = {{id = 'carteiras', kind = 'carteiras', x = 7, y = 4, w = 2, solid = true},
            {id = 'caixas', kind = 'caixas', x = 10, y = 3, solid = true},
            {id = 'brinquedoEscola', kind = 'brinquedo', x = 8, y = 5},
            {id = 'quadroEscola', kind = 'quadro', x = 5, y = 2}},
        npcs = {{id = 'teca', x = 4, y = 4, act = 'teach'}},
        hotspots = {{id = 'escolaRefugio', x = 7, y = 4, range = 1.7, label = 'EXAMINAR'}},
        exits = {{x = 7, y = 9, to = 'hub', arrival = 'escola', localPath = true, label = 'HORTA E TERRAÇO'}},
    },
}
